# Generated by Django 5.2.7 on 2025-11-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
    ]
