# Generated by Django 5.2.7 on 2025-12-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGI', '0002_categorias_lote_producto_proveedores_delete_nadahpta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_total',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cantidad_actual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cantidad_ingresada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
    ]
