# Generated by Django 5.2.7 on 2025-12-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGI', '0003_remove_producto_precio_compra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='catagoria',
            new_name='categoria',
        ),
    ]
