# Generated by Django 5.2.7 on 2026-01-24 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGI', '0004_rename_catagoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='usuario',
            field=models.ForeignKey(default='53bc65f2-7176-4d2e-b92a-7628e74ce1b5', on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario',
            field=models.ForeignKey(default='53bc65f2-7176-4d2e-b92a-7628e74ce1b5', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='usuario',
            field=models.ForeignKey(default='53bc65f2-7176-4d2e-b92a-7628e74ce1b5', on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to=settings.AUTH_USER_MODEL),
        ),
    ]
