# Generated by Django 5.2.7 on 2026-01-24 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGI', '0005_categorias_usuario_producto_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to=settings.AUTH_USER_MODEL),
        ),
    ]
