# Generated by Django 5.2.7 on 2026-02-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGI', '0006_alter_categorias_usuario_alter_producto_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='numero_lote',
        ),
        migrations.AddField(
            model_name='lote',
            name='precio_lote',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
