# Generated by Django 5.2.7 on 2026-02-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGI', '0007_remove_lote_numero_lote_lote_precio_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
    ]
