# Generated by Django 5.2.7 on 2026-03-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGI', '0008_producto_stock_actual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='direccin',
            new_name='direccion',
        ),
    ]
