# Generated by Django 5.2.7 on 2026-03-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGI', '0010_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
