# Generated by Django 5.2.7 on 2026-03-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGI', '0011_delete_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
