# Generated by Django 5.2.7 on 2026-03-17 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SGI', '0012_producto_precio_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
